version: "3.4"

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_DATABASE: symfony
    volumes:
      - ./docker/mysql:/var/lib/mysql:rw
    ports:
      - '3306:3306'

  php:
    depends_on:
      - database
    build:
      context: ./docker/php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      DATABASE_URL: "mysql://root:secret@database:3306/symfony?serverVersion=8&charset=utf8mb4"

  nginx:
    depends_on:
      - php
      - database
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html:ro,cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
