services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'


    App\Repository\:
        resource: '../src/Repository'
        public: true